// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIrhPo_50Qb1nQl98CkH26Lc4MO8qAAr0',
    appId: '1:348174261926:web:ed475c6b174c9f89f95e67',
    messagingSenderId: '348174261926',
    projectId: 'login-7cb0e',
    authDomain: 'login-7cb0e.firebaseapp.com',
    storageBucket: 'login-7cb0e.firebasestorage.app',
    measurementId: 'G-VRB02HB6SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtgyb_YCnm-WhjcscAou19fjJp9w_pr-Y',
    appId: '1:348174261926:android:4720189cc87f6fb7f95e67',
    messagingSenderId: '348174261926',
    projectId: 'login-7cb0e',
    storageBucket: 'login-7cb0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhVtJ6hhFVXDZihXPU4kdDPG4GcycubM',
    appId: '1:348174261926:ios:651a33e826614a71f95e67',
    messagingSenderId: '348174261926',
    projectId: 'login-7cb0e',
    storageBucket: 'login-7cb0e.firebasestorage.app',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhVtJ6hhFVXDZihXPU4kdDPG4GcycubM',
    appId: '1:348174261926:ios:651a33e826614a71f95e67',
    messagingSenderId: '348174261926',
    projectId: 'login-7cb0e',
    storageBucket: 'login-7cb0e.firebasestorage.app',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIrhPo_50Qb1nQl98CkH26Lc4MO8qAAr0',
    appId: '1:348174261926:web:a73e5180bc2d095af95e67',
    messagingSenderId: '348174261926',
    projectId: 'login-7cb0e',
    authDomain: 'login-7cb0e.firebaseapp.com',
    storageBucket: 'login-7cb0e.firebasestorage.app',
    measurementId: 'G-ZVJP26VGZ1',
  );
}
